#!/usr/bin/env bash
set -euo pipefail

# How to add a new module README to the documentation:
#
# 1. Add a new entry to ../modules_readme_config.json:
#
# {
# "name": "my-module",
# "title": "My Module",
# "source": "https://raw.githubusercontent.com/oarepo/my-module/refs/heads/main/README.md",
# "target": "content/modules/my_module/index.mdx"
# }
#
# The source must be a raw README URL, not a GitHub "blob" URL.
#
# 2. Add the module to ../content/modules/_meta.js:
#
# "my_module": {
#   "display": "hidden"
# },
# "my_module_link": {
#   "title": "My Module",
#   "href": "/modules/my_module"
# }
#
# The hidden folder contains the generated README page.
# The *_link item is the visible sidebar link that points directly to that README.
#
# 3. Create ../content/modules/my_module/_meta.js:
#
# export default {
#   "index": {
#     "display": "hidden"
#   }
# }
#
# This hides the generated "index" page from being shown as an expandable
# "Overview" child under the module.
#
# 4. Run this script manually:
#
# ./scripts/sync_modules_readmes.sh
#
# The generated file will be written to:
#
# ../content/modules/my_module/index.mdx

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$SCRIPT_DIR/.."
CONFIG_FILE="$SCRIPT_DIR/../modules_readme_config.json"

if [ ! -f "$CONFIG_FILE" ]; then
echo "Missing $CONFIG_FILE"
exit 1
fi

export REPO_DIR
export CONFIG_FILE

node <<'NODE'
const fs = require("fs");
const path = require("path");

const repoDir = process.env.REPO_DIR;
const configPath = process.env.CONFIG_FILE;
const modules = JSON.parse(fs.readFileSync(configPath, "utf8"));

async function readSource(source) {
const response = await fetch(source);

if (!response.ok) {
throw new Error(`Failed to fetch README: ${source} (${response.status} ${response.statusText})`);
}

return await response.text();
}

async function main() {
for (const module of modules) {
const sourceUrl = module.source;
const targetPath = path.resolve(repoDir, module.target);

const readme = await readSource(sourceUrl);

const output = `{/*
This file is generated from ${module.source}.
Do not edit this file directly. Edit the source README and run:
./scripts/sync_modules_readmes.sh
*/}

${readme}
`;

fs.mkdirSync(path.dirname(targetPath), { recursive: true });
fs.writeFileSync(targetPath, output);

console.log(`Updated ${targetPath} from ${sourceUrl}`);
}
}

main().catch((error) => {
console.error(error);
process.exit(1);
});
NODE
